[package]
org = "choreo"
name = "idCheck"
version = "1.1.0"
export = ["idCheck"]
distribution = "2201.0.1"
keywords = ["Type/RestApi","Category/Service","Internal/http"]
icon = "docs/icon.png"

[build-options]
observabilityIncluded = true
